name: diary
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.1+7

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.1.2
  crypto: ^3.0.0
  encrypt: ^5.0.0
  pointycastle: ^3.1.1
  flutter_secure_storage: ^8.1.0
  google_fonts: ^5.1.0
  html: ^0.15.4
  flutter_html: ^3.0.0-alpha.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
